## **NBA Prospect Evaluator**
##### *Predicting NBA success based on NCAA statistics*

In [1]:
print("Jared Mccain is my favorite nba player of all time")

Jared Mccain is my favorite nba player of all time

In [2]:
# Test Environment
print("Jared McCain")

Jared McCain

# Data Collection

#### Use API to get college basketball player data *(getcollegedata.py)*

In [4]:
from getcollegedata import pull_all_seasons
import os
import pandas as pd

if os.path.exists("data/raw/player_stats_2015_2025.csv"):
    df = pd.read_csv(
        "data/raw/player_stats_2015_2025.csv"
    )
else:
    df = pull_all_seasons(2015, 2025)
    df.to_csv(
        "data/raw/player_stats_2015_2025.csv",
        index=False
    )

In [48]:
college_player_stats = pd.read_csv("data/raw/player_stats_2015_2025.csv")
college_player_stats.columns
college_player_stats.head()

,season,seasonLabel,teamId,team,conference,athleteId,athleteSourceId,name,position,games,...,freeThrows.pct,freeThrows.attempted,freeThrows.made,rebounds.total,rebounds.defensive,rebounds.offensive,winShares.totalPer40,winShares.total,winShares.defensive,winShares.offensive
0,2015,20142015,1,Abilene Christian,Southland,47237,3152345,K.J. Maura,G,17,...,100.0,5,5,24,17,7,0.041,0.2,0.1,0.1
1,2015,20142015,1,Abilene Christian,Southland,47386,3152349,Drake Green,G,28,...,56.3,16,9,22,18,4,-0.049,-0.3,0.1,-0.4
2,2015,20142015,1,Abilene Christian,Southland,47387,3152347,Isaiah Tripp,G,29,...,60.0,25,15,33,20,13,0.057,0.3,0.1,0.2
3,2015,20142015,1,Abilene Christian,Southland,52198,67296,Christian Albright,F,20,...,64.7,17,11,65,44,21,0.015,0.1,0.3,-0.2
4,2015,20142015,1,Abilene Christian,Southland,56233,3155902,Duran Porter,F,31,...,50.0,40,20,71,42,29,0.010,0.1,0.2,-0.1

In [49]:
# Add additional columns
import numpy as np

# Per-game stats
college_player_stats["MPG"] = np.where(
    college_player_stats["games"] > 0,
    college_player_stats["minutes"] / college_player_stats["games"],
    np.nan
)

college_player_stats["PPG"] = np.where(
    college_player_stats["games"] > 0,
    college_player_stats["points"] / college_player_stats["games"],
    np.nan
)

college_player_stats["APG"] = np.where(
    college_player_stats["games"] > 0,
    college_player_stats["assists"] / college_player_stats["games"],
    np.nan
)

college_player_stats["SPG"] = np.where(
    college_player_stats["games"] > 0,
    college_player_stats["steals"] / college_player_stats["games"],
    np.nan
)

college_player_stats["BPG"] = np.where(
    college_player_stats["games"] > 0,
    college_player_stats["blocks"] / college_player_stats["games"],
    np.nan
)

college_player_stats["TPG"] = np.where(
    college_player_stats["games"] > 0,
    college_player_stats["turnovers"] / college_player_stats["games"],
    np.nan
)

college_player_stats["FPG"] = np.where(
    college_player_stats["games"] > 0,
    college_player_stats["fouls"] / college_player_stats["games"],
    np.nan
)

# Per-40 stats
college_player_stats["PTS_PER_40"] = np.where(
    college_player_stats["minutes"] > 0,
    college_player_stats["points"] / college_player_stats["minutes"] * 40,
    np.nan
)

college_player_stats["AST_PER_40"] = np.where(
    college_player_stats["minutes"] > 0,
    college_player_stats["assists"] / college_player_stats["minutes"] * 40,
    np.nan
)

college_player_stats["STL_PER_40"] = np.where(
    college_player_stats["minutes"] > 0,
    college_player_stats["steals"] / college_player_stats["minutes"] * 40,
    np.nan
)

college_player_stats["BLK_PER_40"] = np.where(
    college_player_stats["minutes"] > 0,
    college_player_stats["blocks"] / college_player_stats["minutes"] * 40,
    np.nan
)

college_player_stats["TOV_PER_40"] = np.where(
    college_player_stats["minutes"] > 0,
    college_player_stats["turnovers"] / college_player_stats["minutes"] * 40,
    np.nan
)

college_player_stats["FOULS_PER_40"] = np.where(
    college_player_stats["minutes"] > 0,
    college_player_stats["fouls"] / college_player_stats["minutes"] * 40,
    np.nan
)

# Additional prospect metrics
college_player_stats["AST_TO_TOV"] = np.where(
    college_player_stats["turnovers"] > 0,
    college_player_stats["assists"] / college_player_stats["turnovers"],
    np.nan
)

college_player_stats["STOCKS_PER_40"] = (
    college_player_stats["STL_PER_40"] +
    college_player_stats["BLK_PER_40"]
)

# Round all created columns
new_cols = [
    "MPG", "PPG", "APG", "SPG", "BPG", "TPG", "FPG",
    "PTS_PER_40", "AST_PER_40", "STL_PER_40",
    "BLK_PER_40", "TOV_PER_40", "FOULS_PER_40",
    "AST_TO_TOV", "STOCKS_PER_40"
]

college_player_stats[new_cols] = (
    college_player_stats[new_cols].round(2)
)

NBA Player Data

In [116]:
from pathlib import Path
import pandas as pd

ROOT = Path.cwd()

all_dfs = []


if os.path.exists("data/raw/nba_player_stats_2016_2026.csv"):
    print("File already exists.")
else:
    for year in range(16, 27):  # 16 through 26
        file_path = ROOT / "data" / "raw" / f"nba_player_data_{year}.xlsx"

        print(f"Loading {file_path.name}")

        df = pd.read_excel(file_path)

        # add a season column
        df["Season"] = int(f"20{year}")

        all_dfs.append(df)

    nba_player_stats = pd.concat(all_dfs, ignore_index=True)

    # Save combined dataset
    output_path = ROOT / "data" / "raw" / "nba_player_stats_2016_2026.csv"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    nba_player_stats.to_csv(output_path, index=False)

    print(f"Saved to {output_path}")

Loading nba_player_data_16.xlsx
Loading nba_player_data_17.xlsx
Loading nba_player_data_18.xlsx
Loading nba_player_data_19.xlsx
Loading nba_player_data_20.xlsx
Loading nba_player_data_21.xlsx
Loading nba_player_data_22.xlsx
Loading nba_player_data_23.xlsx
Loading nba_player_data_24.xlsx
Loading nba_player_data_25.xlsx
Loading nba_player_data_26.xlsx
Saved to c:\Users\jftho\OneDrive\Documents\NBA_Prospect_Evaluator\data\raw\nba_player_stats_2016_2026.csv

Clean Data

In [117]:
# Load NBA player stats into dataframe
nba_player_stats = pd.read_csv("data/raw/nba_player_stats_2016_2026.csv")
nba_player_stats.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Season
0,1,James Harden,26,HOU,SG,82,82,3125,710,1617,...,501,612,139,51,374,229,2376,3,"MVP-9,AS",2016
1,2,Stephen Curry,27,GSW,PG,79,79,2700,805,1598,...,430,527,169,15,262,161,2375,2,"MVP-1,AS,NBA1",2016
2,3,Kevin Durant,27,OKC,SF,72,72,2578,698,1381,...,589,361,69,85,250,137,2029,1,"MVP-5,AS,NBA2",2016
3,4,LeBron James,31,CLE,SF,76,76,2709,737,1416,...,565,514,104,49,249,143,1920,3,"MVP-3,DPOY-11,AS,NBA1",2016
4,5,Damian Lillard,25,POR,PG,75,75,2676,618,1474,...,302,512,65,28,242,165,1879,0,"MVP-8,NBA2",2016

In [119]:
# Sort so the row with the most games is first
nba_player_stats = nba_player_stats.sort_values(
    ["Player", "Season", "G"],
    ascending=[True, True, False]
)

# Keep only the first row for each player-season
nba_player_stats = nba_player_stats.drop_duplicates(
    subset=["Player", "Season"],
    keep="first"
).reset_index(drop=True)

In [120]:
# Add columns to nba player stats df
import numpy as np

# Per-game stats
nba_player_stats["MPG"] = np.where(
    nba_player_stats["G"] > 0,
    nba_player_stats["MP"] / nba_player_stats["G"],
    np.nan
)

nba_player_stats["PPG"] = np.where(
    nba_player_stats["G"] > 0,
    nba_player_stats["PTS"] / nba_player_stats["G"],
    np.nan
)

nba_player_stats["APG"] = np.where(
    nba_player_stats["G"] > 0,
    nba_player_stats["AST"] / nba_player_stats["G"],
    np.nan
)

nba_player_stats["RPG"] = np.where(
    nba_player_stats["G"] > 0,
    nba_player_stats["TRB"] / nba_player_stats["G"],
    np.nan
)

nba_player_stats["ORPG"] = np.where(
    nba_player_stats["G"] > 0,
    nba_player_stats["ORB"] / nba_player_stats["G"],
    np.nan
)

nba_player_stats["DRPG"] = np.where(
    nba_player_stats["G"] > 0,
    nba_player_stats["DRB"] / nba_player_stats["G"],
    np.nan
)

# Per-40 stats
nba_player_stats["PTS_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["PTS"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["AST_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["AST"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["REB_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["TRB"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["ORB_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["ORB"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["DRB_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["DRB"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["STL_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["STL"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["BLK_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["BLK"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["TOV_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["TOV"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["PF_PER_40"] = np.where(
    nba_player_stats["MP"] > 0,
    nba_player_stats["PF"] / nba_player_stats["MP"] * 40,
    np.nan
)

nba_player_stats["AST_TO_TOV"] = np.where(
    nba_player_stats["TOV"] > 0,
    nba_player_stats["AST"] / nba_player_stats["TOV"],
    np.nan
)

nba_player_stats["STOCKS_PER_40"] = (
    nba_player_stats["STL_PER_40"] +
    nba_player_stats["BLK_PER_40"]
)

# Round all newly created columns to 2 decimal places
new_cols = [
    "MPG", "PPG", "APG", "RPG", "ORPG", "DRPG",
    "PTS_PER_40", "AST_PER_40", "REB_PER_40",
    "ORB_PER_40", "DRB_PER_40",
    "STL_PER_40", "BLK_PER_40",
    "TOV_PER_40", "PF_PER_40", 
    "AST_TO_TOV", "STOCKS_PER_40"
]

nba_player_stats[new_cols] = nba_player_stats[new_cols].round(2)

In [ ]:
# Check for duplicate names
duplicate_names_same_season = nba_player_stats[
    nba_player_stats.duplicated(
        subset=["Player", "Season"],
        keep=False
    )
].sort_values(["Player", "Season"])

duplicate_names_same_season

# None exist yay!

Empty DataFrame
Columns: [Rk, Player, Age, Team, Pos, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, Trp-Dbl, Awards, Season, MPG, PPG, APG, RPG, ORPG, DRPG, PTS_PER_40, AST_PER_40, REB_PER_40, ORB_PER_40, DRB_PER_40, STL_PER_40, BLK_PER_40, TOV_PER_40, PF_PER_40, AST_TO_TOV, STOCKS_PER_40, first_season]
Index: []

[0 rows x 51 columns]

In [161]:
# Add column called first season
nba_player_stats["first_season"] = (
    nba_player_stats
    .groupby("Player")["Season"]
    .transform("min")
) - 1

# Add total seasons column
nba_player_stats["total_seasons"] = (
    nba_player_stats
    .groupby("Player")["Season"]
    .transform("nunique")
)

Create NBA outcomes dataframe

In [ ]:
# Create success score for each NBA player
nba_success_scores = (
    nba_player_stats
    .groupby("Player")
    .agg(
        first_season=("first_season", "first"),
        total_seasons=("Season", "nunique"),
        career_minutes=("MP", "sum"),
        career_points=("PTS", "sum"),
        career_rebounds=("TRB", "sum"),
        career_assists=("AST", "sum"),
        career_blocks=("BLK", "sum"),
        career_steals=("STL", "sum")
    )
)

nba_success_scores["production_score"] = (
    nba_success_scores["career_points"]
    + 0.5 * nba_success_scores["career_rebounds"]
    + 1.5 * nba_success_scores["career_assists"]
    + 2 * nba_success_scores["career_steals"]
    + 2 * nba_success_scores["career_blocks"]
)

nba_success_scores["success_score"] = (
    nba_success_scores["production_score"]
    / nba_success_scores["total_seasons"]
)

nba_success_scores.reset_index(inplace=True)

In [ ]:
nba_success_scores.sort_values("success_score", ascending=False).head(10)

,Player,first_season,total_seasons,career_minutes,career_points,career_rebounds,career_assists,career_blocks,career_steals,production_score,success_score,clean_name
474,Jeremy Evans,2015,1,251,71,54,2,9,6,131.0,131.0,jeremy evans
199,Damjan Rudež,2015,2,591,157,45,31,2,15,260.0,130.0,damjan rudež
21,Alec Peters,2017,1,225,82,37,12,2,2,126.5,126.5,alec peters
230,DeJuan Blair,2015,1,218,61,57,11,2,8,126.0,126.0,dejuan blair
692,Matt Bonner,2015,1,206,76,27,9,1,6,117.0,117.0,matt bonner
122,C.J. Wilcox,2015,1,167,70,12,10,2,10,115.0,115.0,cj wilcox
18,Alan Anderson,2015,2,500,151,51,25,1,7,230.0,115.0,alan anderson
959,Tony Wroten,2015,1,144,67,21,20,0,3,113.5,113.5,tony wroten
139,Caron Butler,2015,1,176,63,22,10,1,9,109.0,109.0,caron butler
443,Jarell Eddie,2015,1,147,63,23,5,1,5,94.0,94.0,jarell eddie

Clean College Player data

In [131]:
college_player_stats_copy = college_player_stats.copy()

In [132]:
# Remove duplicate player records in same season
college_player_stats_copy = (
    college_player_stats_copy
    .sort_values(["athleteId", "season", "games"])
    .drop_duplicates(
        subset=["athleteId", "season"],
        keep="last"
    )
)

In [ ]:
# Get one row per player corresponding to their final college season 
college_final_season = college_player_stats_copy.loc[
    college_player_stats_copy.groupby("athleteId")["season"].idxmax()
].reset_index(drop=True)


# Remove players with less than 5 games played in their final season
college_final_season =  college_final_season[
    college_final_season["games"] > 5
].copy()

In [183]:
# Filter college final season dataframe
college_final_season = college_final_season[college_final_season['season'] != 2026]

# Dataframe for 2026 college prospects
college_players_26 = college_final_season[college_final_season['season'] == 2026]

Join NBA and College Player Tables

In [163]:
# Clean names before join
from cleaningfunctions import clean_name

college_final_season["clean_name"] = (
    college_final_season["name"].apply(clean_name)
)

nba_success_scores["clean_name"] = (
    nba_success_scores["Player"].apply(clean_name)
)

In [184]:
college_final_season.head(1)

,season,seasonLabel,teamId,team,conference,athleteId,athleteSourceId,name,position,games,...,FPG,PTS_PER_40,AST_PER_40,STL_PER_40,BLK_PER_40,TOV_PER_40,FOULS_PER_40,AST_TO_TOV,STOCKS_PER_40,clean_name
0,2025,20242025,16,Auburn,SEC,1,5174655,Chaney Johnson,F,38,...,2.76,15.54,2.3,1.26,1.49,1.8,4.73,1.27,2.75,chaney johnson

In [164]:
nba_success_scores.head(1)

,Player,first_season,total_seasons,career_minutes,career_points,career_rebounds,career_assists,career_blocks,career_steals,production_score,success_score,clean_name
0,A.J. Green,2022,4,4888,1756,496,312,19,91,2692.0,673.0,aj green

In [152]:
print(nba_success_scores.columns.tolist())

['Player', 'first_season', 'total_seasons', 'career_minutes', 'career_points', 'career_rebounds', 'career_assists', 'career_blocks', 'career_steals', 'production_score', 'success_score', 'clean_name']

In [191]:
# Choose only columns wanted for joined dataframe
college_final_season_for_join = college_final_season[['clean_name', 'season', 'games', 
    'starts', 'minutes', 'points', 'turnovers', 'fouls', 'assists', 'steals', 'blocks', 
    'usage', 'offensiveRating', 'defensiveRating', 'netRating', 'PORPAG', 'effectiveFieldGoalPct', 
    'trueShootingPct', 'assistsTurnoverRatio', 'freeThrowRate', 'offensiveReboundPct', 
    'fieldGoals.pct', 'fieldGoals.attempted', 'fieldGoals.made', 'twoPointFieldGoals.pct', 
    'twoPointFieldGoals.attempted', 'twoPointFieldGoals.made', 'threePointFieldGoals.pct', 
    'threePointFieldGoals.attempted', 'threePointFieldGoals.made', 'freeThrows.pct', 
    'freeThrows.attempted', 'freeThrows.made', 'rebounds.total', 'rebounds.defensive', 
    'rebounds.offensive', 'winShares.totalPer40', 'winShares.total', 'winShares.defensive', 
    'winShares.offensive', 'MPG', 'PPG', 'APG', 'SPG', 'BPG', 'TPG', 'FPG', 'PTS_PER_40', 
    'AST_PER_40', 'STL_PER_40', 'BLK_PER_40', 'TOV_PER_40', 'FOULS_PER_40', 'AST_TO_TOV', 
    'STOCKS_PER_40']]

nba_success_scores_for_join = nba_success_scores[['clean_name', 'first_season', 'success_score']]

In [192]:
# Joined dataframe
merged = college_final_season_for_join.merge(
    nba_success_scores,
    left_on=['clean_name', 'season'],
    right_on=['clean_name', 'first_season'],
    how='left'
)

new_cols = nba_success_scores_for_join.columns.difference(['clean_name', 'first_season'])
merged[new_cols] = merged[new_cols].fillna(0)

In [187]:
# View new dataframe
merged.sample(5)

,clean_name,season,games,starts,minutes,points,turnovers,fouls,assists,steals,...,first_season,total_seasons,career_minutes,career_points,career_rebounds,career_assists,career_blocks,career_steals,production_score,success_score
15156,deaaron fox,2017,36,34,1064,601,87,90,165,53,...,2017.0,9.0,19892.0,12735.0,2352.0,3707.0,240.0,845.0,21641.5,2404.611111
16871,michael calder,2016,34,16,882,341,81,74,83,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000
16425,daryll palmer,2016,33,12,816,239,21,88,30,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000
7167,jalen ricks,2023,12,0,87,21,3,9,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000
14079,james herrick,2018,24,1,110,29,5,24,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000

# Model

In [190]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error, r2_score

# Define target and features
target = 'success_score'

# Drop non-feature columns (identifiers, target, etc.)
drop_cols = ['clean_name', 'season', 'first_season', 'Player', target]
drop_cols = [c for c in drop_cols if c in merged.columns]

X = merged.drop(columns=drop_cols)
y = merged[target]

# Keep only numeric columns
X = X.select_dtypes(include='number')

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# Evaluate
preds = model.predict(X_test)
print("R2:", r2_score(y_test, preds))
print("RMSE:", root_mean_squared_error(y_test, preds))

# Feature importances
importances = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
print(importances)

R2: 0.9617764932282162
RMSE: 28.300870522577565
production_score             0.742914
career_assists               0.091831
career_points                0.081652
career_steals                0.021664
total_seasons                0.021428
                               ...
fieldGoals.attempted         0.000293
points                       0.000291
winShares.offensive          0.000287
AST_PER_40                   0.000242
threePointFieldGoals.made    0.000219
Length: 61, dtype: float64